### ISSUE TITLE
Send Slack message after failed test

### ISSUE THREAD

**Issue by johannes-b** [johannes-b/kubecon22#6]
According to the demo flow, we would like to send a Slack message after a test failed: 

Proposal:

1. Keptn - Staging is green
2. Keptn - Start prod deployment (progressive delivery)
    * Update new version of demo app
    * Start E2E test on new feature
    * E2E test fails
    * **Send Slack message**
        * Screenshot (Optional)
        * Link to Jaeger
    * Troubleshoot auth issue
3. Demo Config update with correct auth token
4. Keptn - Rerun production deployment
    * Update new version of demo app
    * Start E2E test on new feature
    * E2E test passes
    * Update feature flag to be enabled for all users
    * Send slack success message (Optional)

**Comment by johannes-b** [comment]
Found a bug in Keptn that current blocks this issue: https://github.com/keptn/keptn/issues/8731

**Comment by johannes-b** [comment]
Problem resolved.

![image](https://user-images.githubusercontent.com/729071/186617587-21c400e4-0a2f-45bc-b716-11ab45d0d00d.png)


It requires a shipyard config as follows:

```
- name: notify
  triggeredOn:
  - event: production.delivery.finished
    selector:
      match:
        result: "fail"
  tasks:
  - name: notify
```
